var AssetConfig = {
	map: {
		asset: [{
			id: "1-960",
			url: "1-960.png"
		}, {
			id: "1-1136",
			url: "1-1136.png"
		}, {
			id: "2-960",
			url: "2-960.png"
		}, {
			id: "2-1136",
			url: "2-1136.png"
		}, {
			id: "3-960",
			url: "3-960.png"
		}, {
			id: "3-1136",
			url: "3-1136.png"
		}]
	},
	ship: {
		asset: [{
			id: 'cargoShip1JSON',
			url: 'cargoShip1.json'
		}, {
			id: 'cargoShip1',
			url: 'cargo_ship/1.png'
		}, {
			id: 'cargoShip2JSON',
			url: 'cargoShip2.json'
		}, {
			id: 'cargoShip2',
			url: 'cargo_ship/2.png'
		}, {
			id: 'cargoShip3JSON',
			url: 'cargoShip_common.json'
		}, {
			id: 'cargoShip3',
			url: 'cargo_ship/3.png'
		}, {
			id: 'cargoShip4JSON',
			url: 'cargoShip_common.json'
		}, {
			id: 'cargoShip4',
			url: 'cargo_ship/4.png'
		}, {
			id: 'cargoShip5JSON',
			url: 'cargoShip_common.json'
		}, {
			id: 'cargoShip5',
			url: 'cargo_ship/5.png'
		}, {
			id: 'cargoShip6JSON',
			url: 'cargoShip_common.json'
		}, {
			id: 'cargoShip6',
			url: 'cargo_ship/6.png'
		}, {
			id: 'pirateBoat1JSON',
			url: 'pirateBoat1.json'
		}, {
			id: 'pirateBoat1',
			url: 'pirate_boat/1.png'
		}, {
			id: 'pirateBoat2JSON',
			url: 'pirateBoat2.json'
		}, {
			id: 'pirateBoat2',
			url: 'pirate_boat/2.png'
		}, {
			id: 'pirateBoat3JSON',
			url: 'pirateBoat_common.json'
		}, {
			id: 'pirateBoat3',
			url: 'pirate_boat/3.png'
		}, {
			id: 'pirateBoat4JSON',
			url: 'pirateBoat_common.json'
		}, {
			id: 'pirateBoat4',
			url: 'pirate_boat/4.png'
		}, {
			id: 'pirateBoat5JSON',
			url: 'pirateBoat_common.json'
		}, {
			id: 'pirateBoat5',
			url: 'pirate_boat/5.png'
		}, {
			id: 'pirateBoat6JSON',
			url: 'pirateBoat_common.json'
		}, {
			id: 'pirateBoat6',
			url: 'pirate_boat/6.png'
		}, {
			id: 'pirateBoat7JSON',
			url: 'pirateBoat_common.json'
		}, {
			id: 'pirateBoat7',
			url: 'pirate_boat/7.png'
		}, {
			id: 'pirateBoat8JSON',
			url: 'pirateBoat_common.json'
		}, {
			id: 'pirateBoat8',
			url: 'pirate_boat/8.png'
		}, {
			id: 'pirateBoat9JSON',
			url: 'pirateBoat_common.json'
		}, {
			id: 'pirateBoat9',
			url: 'pirate_boat/9.png'
		}, {
			id: "bg_boatbox",
			url: "bg_boatbox.png"
		}]
	},
	num: {
		asset: [{
			id: 'round_-',
			url: 'round/-.png'
		}, {
			id: "round_+",
			url: "round/+.png"
		}, {
			id: "round_0",
			url: 'round/0.png'
		}, {
			id: "round_1",
			url: 'round/1.png'
		}, {
			id: "round_2",
			url: 'round/2.png'
		}, {
			id: "round_3",
			url: 'round/3.png'
		}, {
			id: "round_4",
			url: 'round/4.png'
		}, {
			id: "round_5",
			url: 'round/5.png'
		}, {
			id: "round_6",
			url: 'round/6.png'
		}, {
			id: "round_7",
			url: 'round/7.png'
		}, {
			id: "round_8",
			url: 'round/8.png'
		}, {
			id: "round_9",
			url: 'round/9.png'
		}, {
			id: 'boat_-',
			url: 'boat/-.png'
		}, {
			id: 'boat_+',
			url: 'boat/+.png'
		}, {
			id: "boat_0",
			url: 'boat/0.png'
		}, {
			id: "boat_1",
			url: 'boat/1.png'
		}, {
			id: "boat_2",
			url: 'boat/2.png'
		}, {
			id: "boat_3",
			url: 'boat/3.png'
		}, {
			id: "boat_4",
			url: 'boat/4.png'
		}, {
			id: "boat_5",
			url: 'boat/5.png'
		}, {
			id: "boat_6",
			url: 'boat/6.png'
		}, {
			id: "boat_7",
			url: 'boat/7.png'
		}, {
			id: "boat_8",
			url: 'boat/8.png'
		}, {
			id: "boat_9",
			url: 'boat/9.png'
		}, {
			id: 'coin_-',
			url: 'coin/-.png'
		}, {
			id: "coin_+",
			url: "coin/+.png"
		}, {
			id: "coin_0",
			url: 'coin/0.png'
		}, {
			id: "coin_1",
			url: 'coin/1.png'
		}, {
			id: "coin_2",
			url: 'coin/2.png'
		}, {
			id: "coin_3",
			url: 'coin/3.png'
		}, {
			id: "coin_4",
			url: 'coin/4.png'
		}, {
			id: "coin_5",
			url: 'coin/5.png'
		}, {
			id: "coin_6",
			url: 'coin/6.png'
		}, {
			id: "coin_7",
			url: 'coin/7.png'
		}, {
			id: "coin_8",
			url: 'coin/8.png'
		}, {
			id: "coin_9",
			url: 'coin/9.png'
		}]
	},
	other: {
		asset: [{
			id: "city",
			url: "city.png"
		}, {
			id: "gameScore",
			url: "gameScore.png"
		}, {
			id: "city_h",
			url: "city_h.png"
		}, {
			id: "chooseLevel",
			url: "chooseLevel.png"
		}, {
			id: "chooseLevel_h",
			url: "chooseLevel_h.png"
		}, {
			id: "chooseLevel_bg",
			url: "chooseLevel_bg.png"
		}, {
			id: "btn_back",
			url: "btn_back.png"
		}, {
			id: "btn_turnpage",
			url: "btn_turnpage.png"
		}, {
			id: "shop",
			url: "shop.png"
		}, {
			id: "strengthenBoat",
			url: "strengthenBoat.png"
		}, {
			id: "popupBtn_bg",
			url: "popupBtn_bg.png"
		}, {
			id: "popupBtn_bg-h",
			url: "popupBtn_bg-h.png"
		}, {
			id: "popupBtn1_bg",
			url: "popupBtn1_bg.png"
		}, {
			id: "popupBtn1_bg-h",
			url: "popupBtn1_bg-h.png"
		}, {
			id: "score",
			url: "score.png"
		}, {
			id: "score_h",
			url: "score_h.png"
		}, {
			id: 'scoreNum',
			url: 'scoreNum.png'
		}, {
			id: "badge",
			url: "badge.png"
		}, {
			id: "win",
			url: "win.png"
		}, {
			id: "lose",
			url: "lose.png"
		}, {
			id: "strategy",
			url: "strategy.png"
		}, {
			id: 'bullet',
			url: 'bullet.png'
		}, {
			id: 'explode1JSON',
			url: 'explode1.json'
		}, {
			id: 'explode1',
			url: 'explode1.png'
		}, {
			id: 'explode2JSON',
			url: 'explode2.json'
		}, {
			id: 'explode2',
			url: 'explode2.png'
		}, {
			id: 'warn',
			url: 'warn.png'
		}, {
			id: 'target',
			url: 'target.png'
		}, {
			id: 'choosePirate',
			url: 'choosePirate.png'
		}, {
			id: 'fire',
			url: 'fire.png'
		}, {
			id: 'fireJSON',
			url: 'fire.json'
		}, {
			id: 'coin',
			url: 'coin.png'
		}, {
			id: 'popupBase',
			url: 'popupBase.png'
		}, {
			id: "popupBase1",
			url: "popupBase1.png"
		}, {
			id: 'popupBase_bg',
			url: 'popupBase_bg.png'
		}, {
			id: 'pauseExitButton',
			url: 'pauseExitButton.png'
		}, {
			id: 'pausePlayButton',
			url: 'pausePlayButton.png'
		}, {
			id: 'pauseRestartButton',
			url: 'pauseRestartButton.png'
		}, {
			id: 'xButton',
			url: 'xButton.png'
		}]
	},
	worldmap: {
		asset: [{
			id: "southEastAsia",
			url: "southEastAsia.jpg"
		}, {
			id: "southEastAsia-1",
			url: "southEastAsia-1.png"
		}, {
			id: "southEastAsia-2",
			url: "southEastAsia-2.png"
		}, {
			id: "southEastAsia-3",
			url: "southEastAsia-3.png"
		}, {
			id: "southEastAsia-4",
			url: "southEastAsia-4.png"
		}, {
			id: "southEastAsia-5",
			url: "southEastAsia-5.png"
		}, {
			id: "southEastAsia-6",
			url: "southEastAsia-6.png"
		}, {
			id: "city1-pic",
			url: "citys/1-pic.png"
		}, {
			id: "city1-name",
			url: "citys/1-name.png"
		}]
	},
	menu: {
		asset: [{
			id: "bg",
			url: "bg.png"
		}, {
			id: "bg_box",
			url: "bg_box.png"
		}, {
			id: "boat",
			url: "boat.png"
		}, {
			id: "num",
			url: "num.png"
		}, {
			id: "hammer",
			url: "hammer.png"
		}, {
			id: "hammer-h",
			url: "hammer-h.png"
		}, {
			id: "money",
			url: "money.png"
		}, {
			id: "skill",
			url: "skill.png"
		}, {
			id: "start",
			url: "start.png"
		}, {
			id: "pause",
			url: "pause.png"
		}, {
			id: "warning",
			url: "warning.png"
		}]
	},
	sounds: {
		asset: [{
			id: "chooseLevel",
			url: "chooseLevel.mp3"
		}, {
			id: "explosion",
			url: "explosion.mp3"
		}, {
			id: "fire",
			url: "fire.mp3"
		}, {
			id: "startGame",
			url: "startGame.mp3"
		}]
	}
}